### ISSUE TITLE
Why input can't get focus

### ISSUE THREAD

**Issue by beiluo** [skpm/sketch-module-web-view#129]
```html
    <div>
      <button id="button">Get a random number</button>
    </div>
    <div id="answer"></div>
    <input type="text" />
```
```css
*, *:before, *:after {
  box-sizing: inherit;
  margin: 0;
  padding: 0;
  position: relative;

  /* Prevent the content from being selectionable */
  -webkit-user-select: none;
  user-select: none;
}

input, textarea {
  -webkit-user-select: auto;
  user-select: auto;
}
```
OS:mac OS Catalina 10.15
Sketch:53
